# -*- coding: utf-8 -*-

import sys
import re as re_
import base64
import datetime as datetime_
import warnings as warnings_

try:
    from lxml import etree as etree_
except ImportError:
    from xml.etree import ElementTree as etree_

Validate_simpletypes_ = True
if sys.version_info.major == 2:
    BaseStrType_ = basestring
else:
    BaseStrType_ = str

#
# Namespace prefix definition table (and other attributes, too)
#
# The module generatedsnamespaces, if it is importable, must contain
# a dictionary named GeneratedsNamespaceDefs.  This Python dictionary
# should map element type names (strings) to XML schema namespace prefix
# definitions.  The export method for any class for which there is
# a namespace prefix definition, will export that definition in the
# XML representation of that element.  See the export method of
# any generated element type class for a example of the use of this
# table.
# A sample table is:
#
#     # File: generatedsnamespaces.py
#
#     GenerateDSNamespaceDefs = {
#         "ElementtypeA": "http://www.xxx.com/namespaceA",
#         "ElementtypeB": "http://www.xxx.com/namespaceB",
#     }
#

try:
    from generatedsnamespaces import GenerateDSNamespaceDefs as GenerateDSNamespaceDefs_
except ImportError:
    GenerateDSNamespaceDefs_ = {}

#
# The root super-class for element type classes
#
# Calls to the methods in these classes are generated by generateDS.py.
# You can replace these methods by re-implementing the following class
#   in a module named generatedssuper.py.

try:
    from generatedssuper import GeneratedsSuper
except ImportError as exp:

    class GeneratedsSuper(object):
        tzoff_pattern = re_.compile(r'(\+|-)((0\d|1[0-3]):[0-5]\d|14:00)$')

        class _FixedOffsetTZ(datetime_.tzinfo):
            def __init__(self, offset, name):
                self.__offset = datetime_.timedelta(minutes=offset)
                self.__name = name

            def utcoffset(self, dt):
                return self.__offset

            def tzname(self, dt):
                return self.__name

            def dst(self, dt):
                return None

        def gds_format_string(self, input_data, input_name=''):
            return input_data

        def gds_validate_string(self, input_data, node=None, input_name=''):
            if not input_data:
                return ''
            else:
                return input_data

        def gds_format_base64(self, input_data, input_name=''):
            return base64.b64encode(input_data)

        def gds_validate_base64(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_integer(self, input_data, input_name=''):
            return '%d' % input_data

        def gds_validate_integer(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_integer_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)

        def gds_validate_integer_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    int(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of integers')
            return values

        def gds_format_float(self, input_data, input_name='', digits=2):
            # return ('%.15f' % input_data).rstrip('0') # sguzman 2019-05-27
            # return ('%f' % input_data)
            return '%.{}f'.format(digits) % input_data

        def gds_validate_float(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_float_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)

        def gds_validate_float_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of floats')
            return values

        def gds_format_double(self, input_data, input_name=''):
            return '%e' % input_data

        def gds_validate_double(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_double_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)

        def gds_validate_double_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of doubles')
            return values

        def gds_format_boolean(self, input_data, input_name=''):
            return ('%s' % input_data).lower()

        def gds_validate_boolean(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_boolean_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)

        def gds_validate_boolean_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                if value not in ('true', '1', 'false', '0',):
                    raise_parse_error(
                        node,
                        'Requires sequence of booleans '
                        '("true", "1", "false", "0")')
            return values

        def gds_validate_datetime(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_datetime(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d.%s' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue

        @classmethod
        def gds_parse_datetime(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            time_parts = input_data.split('.')
            if len(time_parts) > 1:
                micro_seconds = int(float('0.' + time_parts[1]) * 1000000)
                input_data = '%s.%s' % (time_parts[0], micro_seconds,)
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt

        def gds_validate_date(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_date(self, input_data, input_name=''):
            _svalue = '%02d-%02d-%04d' % (
                input_data.day,
                input_data.month,
                input_data.year,
            )
            try:
                if input_data.tzinfo is not None:
                    tzoff = input_data.tzinfo.utcoffset(input_data)
                    if tzoff is not None:
                        total_seconds = tzoff.seconds + (86400 * tzoff.days)
                        if total_seconds == 0:
                            _svalue += 'Z'
                        else:
                            if total_seconds < 0:
                                _svalue += '-'
                                total_seconds *= -1
                            else:
                                _svalue += '+'
                            hours = total_seconds // 3600
                            minutes = (total_seconds - (hours * 3600)) // 60
                            _svalue += '{0:02d}:{1:02d}'.format(
                                hours, minutes)
            except AttributeError:
                pass
            return _svalue

        @classmethod
        def gds_parse_date(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            dt = datetime_.datetime.strptime(input_data, '%Y-%m-%d')
            dt = dt.replace(tzinfo=tz)
            return dt.date()

        def gds_validate_time(self, input_data, node=None, input_name=''):
            return input_data

        def gds_format_time(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%02d:%02d:%02d' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%02d:%02d:%02d.%s' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue

        def gds_validate_simple_patterns(self, patterns, target):
            # pat is a list of lists of strings/patterns.  We should:
            # - AND the outer elements
            # - OR the inner elements
            found1 = True
            for patterns1 in patterns:
                found2 = False
                for patterns2 in patterns1:
                    if re_.search(patterns2, target) is not None:
                        found2 = True
                        break
                if not found2:
                    found1 = False
                    break
            return found1

        @classmethod
        def gds_parse_time(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            if len(input_data.split('.')) > 1:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt.time()

        def gds_str_lower(self, instring):
            return instring.lower()

        def get_path_(self, node):
            path_list = []
            self.get_path_list_(node, path_list)
            path_list.reverse()
            path = '/'.join(path_list)
            return path

        Tag_strip_pattern_ = re_.compile(r'\{.*\}')

        def get_path_list_(self, node, path_list):
            if node is None:
                return
            tag = GeneratedsSuper.Tag_strip_pattern_.sub('', node.tag)
            if tag:
                path_list.append(tag)
            self.get_path_list_(node.getparent(), path_list)

        def get_class_obj_(self, node, default_class=None):
            class_obj1 = default_class
            if 'xsi' in node.nsmap:
                classname = node.get('{%s}type' % node.nsmap['xsi'])
                if classname is not None:
                    names = classname.split(':')
                    if len(names) == 2:
                        classname = names[1]
                    class_obj2 = globals().get(classname)
                    if class_obj2 is not None:
                        class_obj1 = class_obj2
            return class_obj1

        def gds_build_any(self, node, type_name=None):
            return None

        @classmethod
        def gds_reverse_node_mapping(cls, mapping):
            return dict(((v, k) for k, v in mapping.iteritems()))

        @staticmethod
        def gds_encode(instring):
            if sys.version_info.major == 2:
                return instring.encode(ExternalEncoding)
            else:
                return instring

        @staticmethod
        def convert_unicode(instring):
            if isinstance(instring, str):
                result = quote_xml(instring)
            elif sys.version_info.major == 2 and isinstance(instring, unicode):
                result = quote_xml(instring).encode('utf8')
            else:
                result = GeneratedsSuper.gds_encode(str(instring))
            return result

        def __eq__(self, other):
            if type(self) != type(other):
                return False
            return self.__dict__ == other.__dict__

        def __ne__(self, other):
            return not self.__eq__(other)


    def getSubclassFromModule_(module, class_):
        '''Get the subclass of a class from a specific module.'''
        name = class_.__name__ + 'Sub'
        if hasattr(module, name):
            return getattr(module, name)
        else:
            return None

#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#

## from IPython.Shell import IPShellEmbed
## args = ''
## ipshell = IPShellEmbed(args,
##     banner = 'Dropping into IPython',
##     exit_msg = 'Leaving Interpreter, back to program.')

# Then use the following line where and when you want to drop into the
# IPython shell:
#    ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')

#
# Globals
#

ExternalEncoding = 'utf-8'
Tag_pattern_ = re_.compile(r'({.*})?(.*)')
String_cleanup_pat_ = re_.compile(r"[\n\r\s]+")
Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
CDATA_pattern_ = re_.compile(r"<!\[CDATA\[.*?\]\]>", re_.DOTALL)

# Change this to redirect the generated superclass module to use a
# specific subclass module.
CurrentSubclassModule_ = None


#
# Support/utility functions.
#


def showIndent(outfile, level, pretty_print=True):
    if pretty_print:
        for idx in range(level):
            outfile.write(b'    ')


def quote_xml(inStr):
    "Escape markup chars, but do not modify CDATA sections."
    if not inStr:
        return ''
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
    s2 = ''
    pos = 0
    matchobjects = CDATA_pattern_.finditer(s1)
    for mo in matchobjects:
        s3 = s1[pos:mo.start()]
        s2 += quote_xml_aux(s3)
        s2 += s1[mo.start():mo.end()]
        pos = mo.end()
    s3 = s1[pos:]
    s2 += quote_xml_aux(s3)
    return s2


def quote_xml_aux(inStr):
    s1 = inStr.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1


def quote_attrib(inStr):
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1


def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1


def get_all_text_(node):
    if node.text is not None:
        text = node.text
    else:
        text = ''
    for child in node:
        if child.tail is not None:
            text += child.tail
    return text


def find_attr_value_(attr_name, node):
    attrs = node.attrib
    attr_parts = attr_name.split(':')
    value = None
    if len(attr_parts) == 1:
        value = attrs.get(attr_name)
    elif len(attr_parts) == 2:
        prefix, name = attr_parts
        namespace = node.nsmap.get(prefix)
        if namespace is not None:
            value = attrs.get('{%s}%s' % (namespace, name,))
    return value


class GDSParseError(Exception):
    pass


def raise_parse_error(node, msg):
    msg = '%s (element %s/line %d)' % (msg, node.tag, node.sourceline,)
    raise GDSParseError(msg)


#
# Data representation classes.
#


class ResumenFacturaConsumoElectronica(GeneratedsSuper):
    """Formato de Resumen Factura de Consumo Electrónica <DOP250,000 (RFCE)"""
    subclass = None
    superclass = None

    def __init__(self, Encabezado, DescuentosORecargos=None):
        self.original_tagname_ = None
        self.Encabezado = Encabezado
        self.DescuentosORecargos = DescuentosORecargos

    def get_Encabezado(self):
        return self.Encabezado

    def set_Encabezado(self, Encabezado):
        self.Encabezado = Encabezado

    def get_DescuentosORecargos(self):
        return self.DescuentosORecargos

    def set_DescuentosORecargos(self, DescuentosORecargos):
        self.DescuentosORecargos = DescuentosORecargos
    
    def hasContent_(self):
        if (
                self.Encabezado is not None or
                self.DescuentosORecargos is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='RFCE', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('RFCE')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='ECF', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='RFCE', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''

        if self.Encabezado is not None:
            self.Encabezado.export(outfile, level, namespace_, name_='Encabezado', pretty_print=pretty_print)
        if self.DescuentosORecargos is not None:
            self.DescuentosORecargos.export(outfile, level, namespace_, name_='DescuentosORecargos',
                                            pretty_print=pretty_print)


class Encabezado(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, Version, IdDoc, Emisor, Totales, CodigoSeguridadeCF=None, Comprador=None):  # CodigoSeguridadeCF si es obligatorio
        self.original_tagname_ = None
        self.Version = Version
        self.IdDoc = IdDoc
        self.Emisor = Emisor
        self.Comprador = Comprador
        self.Totales = Totales
        self.CodigoSeguridadeCF = CodigoSeguridadeCF

    def get_Version(self):
        return self.Version

    def set_Version(self, Version):
        self.Version = Version

    def get_IdDoc(self):
        return self.IdDoc

    def set_IdDoc(self, IdDoc):
        self.IdDoc = IdDoc

    def get_Emisor(self):
        return self.Emisor

    def set_Emisor(self, Emisor):
        self.Emisor = Emisor

    def get_Comprador(self):
        return self.Comprador

    def set_Comprador(self, Comprador):
        self.Comprador = Comprador

    def get_Totales(self):
        return self.Totales

    def set_Totales(self, Totales):
        self.Totales = Totales

    def get_CodigoSeguridadeCF(self):
        return self.CodigoSeguridadeCF

    def set_CodigoSeguridadeCF(self, CodigoSeguridadeCF):
        self.CodigoSeguridadeCF = CodigoSeguridadeCF

    def hasContent_(self):
        if (
                self.Version is not None or
                self.TipoeCF is not None or
                self.Emisor is not None or
                self.Comprador is not None or
                self.Totales is not None or
                self.CodigoSeguridadeCF is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='Encabezado', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('Encabezado')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(
            bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Encabezado', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='EmisorType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.Version is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<Version>%s</Version>%s' % (
                self.gds_encode(self.gds_format_string(quote_xml(self.Version), input_name='Version')),
                eol_)).encode()))
        if self.IdDoc is not None:
            self.IdDoc.export(outfile, level, namespace_, name_='IdDoc', pretty_print=pretty_print)
        if self.Emisor is not None:
            self.Emisor.export(outfile, level, namespace_, name_='Emisor', pretty_print=pretty_print)
        if self.Comprador is not None:
            self.Comprador.export(outfile, level, namespace_, name_='Comprador', pretty_print=pretty_print)
        if self.Totales is not None:
            self.Totales.export(outfile, level, namespace_, name_='Totales', pretty_print=pretty_print)
        if self.CodigoSeguridadeCF is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<CodigoSeguridadeCF>%s</CodigoSeguridadeCF>%s' % (
                self.gds_encode(
                    self.gds_format_string(quote_xml(self.CodigoSeguridadeCF), input_name='CodigoSeguridadeCF')),
                eol_)).encode()))

    # end class Encabezado


class IdDoc(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, TipoeCF, eNCF, TipoIngresos, TipoPago):
        self.original_tagname_ = None
        self.TipoeCF = TipoeCF
        self.eNCF = eNCF
        self.TipoIngresos = TipoIngresos
        self.TipoPago = TipoPago

    def get_TipoeCF(self):
        return self.TipoeCF

    def set_TipoeCF(self, TipoeCF):
        self.TipoeCF = TipoeCF

    def get_eNCF(self):
        return self.eNCF

    def set_eNCF(self, eNCF):
        self.eNCF = eNCF

    def get_TipoIngresos(self):
        return self.TipoIngresos

    def set_TipoIngresos(self, TipoIngresos):
        self.TipoIngresos = TipoIngresos

    def get_TipoPago(self):
        return self.TipoPago

    def set_TipoPago(self, TipoPago):
        self.TipoPago = TipoPago

    def hasContent_(self):
        if (
                self.TipoeCF is not None or
                self.eNCF is not None or
                self.TipoIngresos is not None or
                self.TipoPago is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='IdDoc', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('IdDoc')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(
            bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='IdDoc', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='EmisorType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.TipoeCF is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TipoeCF>%s</TipoeCF>%s' % (
                self.gds_encode(
                    self.gds_format_string(quote_xml(self.TipoeCF), input_name='Tipo Comprobante Fiscal Electrónico')),
                eol_)).encode()))
        if self.eNCF is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<eNCF>%s</eNCF>%s' % (
                self.gds_encode(
                    self.gds_format_string(quote_xml(self.eNCF), input_name='eNCF')),
                eol_)).encode()))
        if self.TipoIngresos is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TipoIngresos>%s</TipoIngresos>%s' % (
                self.gds_encode(
                    self.gds_format_string(quote_xml(self.TipoIngresos), input_name='TipoIngresos')),
                eol_)).encode()))
        if self.TipoPago is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TipoPago>%s</TipoPago>%s' % (
                self.gds_encode(
                    self.gds_format_string(quote_xml(self.TipoPago), input_name='TipoPago')),
                eol_)).encode()))

    # end class IdDoc


class TablaFormasPago(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, FormaDePago=None):
        self.original_tagname_ = None
        if FormaDePago is None:
            self.FormaDePago = []
        else:
            self.FormaDePago = FormaDePago

    def get_FormaDePago(self):
        return self.FormaDePago

    def set_FormaDePago(self, FormaDePago):
        self.FormaDePago = FormaDePago

    def add_FormaDePago(self, value):
        self.FormaDePago.append(value)

    def insert_FormaDePago_at(self, index, value):
        self.FormaDePago.insert(index, value)

    def replace_FormaDePago_at(self, index, value):
        self.FormaDePago[index] = value

    def hasContent_(self):
        if (
                self.FormaDePago is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='FormaDePago', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('FormaDePago')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(
            bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='FormaDePago', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='DetalleServicioType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for LeneaMago in self.FormaDePago:
            LeneaMago.export(outfile, level, namespace_, name_='FormaDePago', pretty_print=pretty_print)

    # end class TablaFormasPago


class FormaDePago(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, FormaPago=None, MontoPago=None):
        self.original_tagname_ = None
        self.FormaPago = FormaPago
        self.MontoPago = MontoPago

    def get_FormaPago(self):
        return self.Version

    def set_FormaPago(self, FormaPago):
        self.FormaPago = FormaPago

    def get_MontoPago(self):
        return self.MontoPago

    def set_MontoPago(self, MontoPago):
        self.MontoPago = MontoPago

    def hasContent_(self):
        if (
                self.FormaPago is not None or
                self.MontoPago is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='FormaDePago', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('FormaDePago')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(
            bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='FormaDePago', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='EmisorType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.FormaPago is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<FormaPago>%s</FormaPago>%s' % (
                self.gds_format_integer(self.FormaPago, input_name='FormaPago'), eol_)).encode()))
        if self.MontoPago is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoPago>%s</MontoPago>%s' % (
                self.gds_encode(
                    self.gds_format_string(quote_xml(self.MontoPago), input_name='MontoPago')),
                eol_)).encode()))

    # end class FormaDePago


class Emisor(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, RNCEmisor, RazonSocialEmisor, FechaEmision):
        self.original_tagname_ = None
        self.RNCEmisor = RNCEmisor
        self.RazonSocialEmisor = RazonSocialEmisor
        self.FechaEmision = FechaEmision

    def get_RNCEmisor(self):
        return self.RNCEmisor

    def set_RNCEmisor(self, RNCEmisor):
        self.RNCEmisor = RNCEmisor

    def get_RazonSocialEmisor(self):
        return self.RazonSocialEmisor

    def set_RazonSocialEmisor(self, RazonSocialEmisor):
        self.RazonSocialEmisor = RazonSocialEmisor

    def get_NombreComercial(self):
        return self.NombreComercial

    def get_FechaEmision(self):
        return self.FechaEmision

    def set_FechaEmision(self, FechaEmision):
        self.FechaEmision = FechaEmision

    def hasContent_(self):
        if (
                self.RNCEmisor is not None or
                self.RazonSocialEmisor is not None or
                self.FechaEmision is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='EmisorType', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('EmisorType')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(
            bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='EmisorType', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='EmisorType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.RNCEmisor is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<RNCEmisor>%s</RNCEmisor>%s' % (
                self.gds_encode(self.gds_format_string(quote_xml(self.RNCEmisor), input_name='RNC Emisor')),
                eol_)).encode()))
        if self.RazonSocialEmisor is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<RazonSocialEmisor>%s</RazonSocialEmisor>%s' % (
                self.gds_encode(self.gds_format_string(quote_xml(self.RazonSocialEmisor),
                                                       input_name='Nombre o Razón Social del emisor')),
                eol_)).encode()))
        if self.FechaEmision is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<FechaEmision>%s</FechaEmision>%s' % (
                self.gds_format_date(self.FechaEmision, input_name='FechaEmision'), eol_)).encode()))

    # end class Emisor


class Comprador(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, RNCComprador=None, IdentificadorExtranjero=None, RazonSocialComprador=None):
        self.original_tagname_ = None
        self.RNCComprador = RNCComprador
        self.IdentificadorExtranjero = IdentificadorExtranjero
        self.RazonSocialComprador = RazonSocialComprador

    def get_RNCComprador(self):
        return self.RNCComprador

    def set_RNCComprador(self, RNCComprador):
        self.RNCComprador = RNCComprador

    def get_IdentificadorExtranjero(self):
        return self.IdentificadorExtranjero

    def set_IdentificadorExtranjero(self, IdentificadorExtranjero):
        self.IdentificadorExtranjero = IdentificadorExtranjero

    def get_RazonSocialComprador(self):
        return self.RazonSocialComprador

    def set_RazonSocialComprador(self, RazonSocialComprador):
        self.RazonSocialComprador = RazonSocialComprador

    def hasContent_(self):
        if (
                self.RNCComprador is not None or
                self.IdentificadorExtranjero is not None or
                self.RazonSocialComprador is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='CompradorType', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('CompradorType')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='CompradorType', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='ReceptorType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.RNCComprador is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<RNCComprador>%s</RNCComprador>%s' % (
                self.gds_encode(self.gds_format_string(quote_xml(self.RNCComprador), input_name='RNC Comprador')),
                eol_)).encode()))
        if self.IdentificadorExtranjero is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<IdentificadorExtranjero>%s</IdentificadorExtranjero>%s' % (
                self.gds_format_integer(self.IdentificadorExtranjero, input_name='Identificador Extranjero'),
                eol_)).encode()))
        if self.RazonSocialComprador is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<RazonSocialComprador>%s</RazonSocialComprador>%s' % (
                self.gds_encode(self.gds_format_string(quote_xml(self.RazonSocialComprador),
                                                       input_name='Nombre o Razón Social Comprador')), eol_)).encode()))
# end class Comprador


class Totales(GeneratedsSuper):
    subclass = None
    superclass = None

    def __init__(self, MontoTotal, MontoGravadoTotal=0.00, MontoGravadoI1=0.00, MontoGravadoI2=0.00,
                 MontoGravadoI3=0.00, MontoExento=0.00, TotalITBIS=0.00,
                 TotalITBIS1=0.00, TotalITBIS2=0.00, TotalITBIS3=0.00, MontoImpuestoAdicional=None,):
        self.original_tagname_ = None

        self.MontoGravadoTotal = MontoGravadoTotal
        self.MontoGravadoI1 = MontoGravadoI1
        self.MontoGravadoI2 = MontoGravadoI2
        self.MontoGravadoI3 = MontoGravadoI3
        self.MontoExento = MontoExento
        self.TotalITBIS2 = TotalITBIS2
        self.TotalITBIS3 = TotalITBIS3
        self.TotalITBIS = TotalITBIS
        self.TotalITBIS1 = TotalITBIS1
        self.MontoTotal = MontoTotal
        self.MontoImpuestoAdicional = MontoImpuestoAdicional

    def get_MontoGravadoTotal(self):
        return self.MontoGravadoTotal

    def set_MontoGravadoTotal(self, MontoGravadoTotal):
        self.MontoGravadoTotal = MontoGravadoTotal

    def get_MontoGravadoI1(self):
        return self.MontoGravadoI1

    def set_MontoGravadoI1(self, MontoGravadoI1):
        self.MontoGravadoI1 = MontoGravadoI1

    def get_MontoGravadoI2(self):
        return self.MontoGravadoI2

    def set_MontoGravadoI2(self, MontoGravadoI2):
        self.MontoGravadoI2 = MontoGravadoI2

    def get_MontoGravadoI3(self):
        return self.MontoGravadoI3

    def set_MontoGravadoI3(self, MontoGravadoI3):
        self.MontoGravadoI3 = MontoGravadoI3

    def get_MontoExento(self):
        return self.MontoExento

    def set_MontoExento(self, MontoExento):
        self.MontoExento = MontoExento

    def get_TotalITBIS(self):
        return self.TotalITBIS

    def set_TotalITBIS(self, TotalITBIS):
        self.TotalITBIS = TotalITBIS

    def get_TotalITBIS1(self):
        return self.TotalITBIS1

    def set_TotalITBIS1(self, TotalITBIS1):
        self.TotalITBIS1 = TotalITBIS1

    def get_TotalITBIS2(self):
        return self.TotalITBIS2

    def set_TotalITBIS2(self, TotalITBIS2):
        self.TotalITBIS2 = TotalITBIS2

    def get_TotalITBIS3(self):
        return self.TotalITBIS3

    def set_TotalITBIS3(self, TotalITBIS3):
        self.TotalITBIS3 = TotalITBIS3

    def get_MontoTotal(self):
        return self.MontoTotal

    def set_MontoTotal(self, MontoTotal):
        self.MontoTotal = MontoTotal

    def get_MontoImpuestoAdicional(self):
        return self.MontoImpuestoAdicional

    def set_MontoImpuestoAdicional(self, MontoImpuestoAdicional):
        self.MontoImpuestoAdicional = MontoImpuestoAdicional

    def hasContent_(self):
        if (
                self.MontoGravadoTotal is not None or
                self.MontoGravadoI1 is not None or
                self.MontoGravadoI2 is not None or
                self.MontoGravadoI3 is not None or
                self.MontoExento is not None or
                self.TotalITBIS is not None or
                self.TotalITBIS1 is not None or
                self.TotalITBIS2 is not None or
                self.TotalITBIS3 is not None or
                self.MontoTotal is not None or
                self.MontoImpuestoAdicional is not None
        ):
            return True
        else:
            return False

    def export(self, outfile, level, namespace_='', name_='Totales', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('Totales')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write(bytes(('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '',)).encode()))
        if self.hasContent_():
            outfile.write(bytes(('>%s' % (eol_,)).encode()))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Totales', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('</%s%s>%s' % (namespace_, name_, eol_)).encode()))
        else:
            outfile.write(bytes(('/>%s' % (eol_,)).encode()))

    def exportChildren(self, outfile, level, namespace_='', name_='ReceptorType', fromsubclass_=False,
                       pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''

        if self.MontoGravadoTotal is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoGravadoTotal>%s</MontoGravadoTotal>%s' % (
                self.gds_format_float(self.MontoGravadoTotal, input_name='Monto Gravado Total'), eol_)).encode()))
        if self.MontoGravadoI1 is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoGravadoI1>%s</MontoGravadoI1>%s' % (
                self.gds_format_float(self.MontoGravadoI1, input_name='Monto Gravado ITBIS Tasa 1'), eol_)).encode()))
        if self.MontoGravadoI2 is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoGravadoI2>%s</MontoGravadoI2>%s' % (
                self.gds_format_float(self.MontoGravadoI2, input_name='Monto Gravado ITBIS Tasa 2'), eol_)).encode()))
        if self.MontoGravadoI3 is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoGravadoI3>%s</MontoGravadoI3>%s' % (
                self.gds_format_float(self.MontoGravadoI3, input_name='Monto Gravado ITBIS Tasa 3'), eol_)).encode()))
        if self.MontoExento is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoExento>%s</MontoExento>%s' % (
                self.gds_format_float(self.MontoExento, input_name='Monto Exento'), eol_)).encode()))
        if self.TotalITBIS is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TotalITBIS>%s</TotalITBIS>%s' % (
                self.gds_format_float(self.TotalITBIS, input_name='Total ITBIS'), eol_)).encode()))
        if self.TotalITBIS1 is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TotalITBIS1>%s</TotalITBIS1>%s' % (
                self.gds_format_float(self.TotalITBIS1, input_name='Total ITBIS Tasa 1'), eol_)).encode()))
        if self.TotalITBIS2 is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TotalITBIS2>%s</TotalITBIS2>%s' % (
                self.gds_format_float(self.TotalITBIS2, input_name='Total ITBIS Tasa 2'), eol_)).encode()))
        if self.TotalITBIS3 is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<TotalITBIS3>%s</TotalITBIS3>%s' % (
                self.gds_format_float(self.TotalITBIS3, input_name='Total ITBIS Tasa 3'), eol_)).encode()))
        if self.MontoImpuestoAdicional is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoImpuestoAdicional>%s</MontoImpuestoAdicional>%s' % (
                self.gds_format_float(self.MontoImpuestoAdicional, input_name='MontoImpuestoAdicional'),
                eol_)).encode()))
        if self.MontoTotal is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write(bytes(('<MontoTotal>%s</MontoTotal>%s' % (
                self.gds_format_float(self.MontoTotal, input_name='Monto Total'), eol_)).encode()))


# end class Totales
